#!/usr/bin/env python3
"""Rebuild cinevault_catalog.json and sync it into index.html.

The catalog is the single source of truth for the library. It lives in
cinevault_catalog.json (for import/export and editing) and is also embedded in
index.html so the app runs from a plain file:// open with no fetch and no
server. Run this script after editing tools/enrichment.py or the catalog and it
keeps both copies identical.

    python3 tools/build_catalog.py
"""

import json
import os
import re
import sys
from urllib.parse import quote

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from enrichment import ENRICHMENT, BROKEN_POSTERS, CERTIFICATIONS  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "cinevault_catalog.json")
INDEX = os.path.join(ROOT, "index.html")

BEGIN = "    /* CATALOG:BEGIN - generated by tools/build_catalog.py */"
END = "    /* CATALOG:END */"

# Titles as they should read in the catalog.
TITLE_FIXES = {
    "Sonic The Hedgehog": "Sonic the Hedgehog",
    "Winnie The Pooh": "Winnie the Pooh",
}

# Field order in the emitted JSON, so diffs stay readable.
FIELD_ORDER = [
    "id", "title", "year", "rating", "runtime", "certification", "genre",
    "collection", "director", "cast", "synopsis", "poster_url",
    "backdrop_url", "youtube_url", "google_play_url", "trailer_key",
    "ownership", "added", "watched", "favorite", "tags", "notes",
]

# The library records how each title was acquired as a free-form tag. Promote
# that to a real field so it can be filtered on.
OWNERSHIP_FROM_TAG = {"Purchased": "Purchased", "Rental History": "Rented"}


def is_placeholder(url):
    """True for the stock photo that 40 of the 57 titles shared."""
    return not url or "images.unsplash.com" in url


def build():
    with open(CATALOG) as fh:
        movies = json.load(fh)

    out = []
    for index, movie in enumerate(movies):
        m = dict(movie)
        m["title"] = TITLE_FIXES.get(m["title"], m["title"])
        m.update(ENRICHMENT.get(m["id"], {}))

        # Drop artwork we know does not resolve: the shared stock photo and the
        # two malformed TMDB paths. The app draws its own poster instead.
        if is_placeholder(m.get("poster_url")) or m["id"] in BROKEN_POSTERS:
            m["poster_url"] = None
        if is_placeholder(m.get("backdrop_url")) or m["id"] in BROKEN_POSTERS:
            m["backdrop_url"] = None

        query = quote(m["title"])
        m["youtube_url"] = f"https://www.youtube.com/results?search_query={query}+movie"
        m["google_play_url"] = f"https://play.google.com/store/search?q={query}&c=movies"

        m.setdefault("cast", [])
        m.setdefault("tags", [])
        m.setdefault("trailer_key", None)
        m["certification"] = CERTIFICATIONS.get(m["id"])

        ownership = next(
            (OWNERSHIP_FROM_TAG[t] for t in m["tags"] if t in OWNERSHIP_FROM_TAG), None
        )
        m["ownership"] = ownership

        # Sort key for "recently added". Shipped titles keep their catalog
        # order; titles added in the app stamp a timestamp instead.
        m["added"] = index + 1

        ordered = {k: m[k] for k in FIELD_ORDER if k in m}
        ordered.update({k: v for k, v in m.items() if k not in ordered})
        out.append(ordered)

    payload = json.dumps(out, indent=2, ensure_ascii=False)

    with open(CATALOG, "w") as fh:
        fh.write(payload + "\n")

    with open(INDEX) as fh:
        html = fh.read()

    block = f"{BEGIN}\n    const INITIAL_MOVIES = {payload};\n{END}"
    pattern = re.compile(
        re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL
    )
    if not pattern.search(html):
        raise SystemExit(
            "CATALOG:BEGIN/END markers not found in index.html - cannot sync."
        )
    html = pattern.sub(lambda _: block, html)

    with open(INDEX, "w") as fh:
        fh.write(html)

    with_art = sum(1 for m in out if m.get("poster_url"))
    with_synopsis = sum(1 for m in out if m.get("synopsis"))
    print(f"{len(out)} titles written to cinevault_catalog.json and index.html")
    print(f"  {with_art} with TMDB artwork, {len(out) - with_art} using generated art")
    print(f"  {with_synopsis} with synopsis, {sum(1 for m in out if m.get('director'))} with director")
    print(f"  {sum(1 for m in out if m.get('certification'))} rated, "
          f"{sum(1 for m in out if m.get('ownership'))} with ownership")


if __name__ == "__main__":
    build()
